version: '3'

services:
  activemq:
    image: webcenter/activemq:latest
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # TCP
      - "61613:61613" # STOMP
