  spring:
    application:
        name: spring-agent

  decorator.datasource:
      p6spy:
        enable-logging: false

  inspector:
    enabled: ${ENABLED:true}
    url: ${URL:https://ingest.inspector.dev}
    version: ${VERSION:1.0.0}
    max-entries: ${MAX_ENTRIES:500}