  spring:
    application:
        name: spring-agent

  decorator.datasource:
      p6spy:
        enable-logging: false

  inspector:
    enabled: ${INSPECTOR_ENABLED:true}
    url: ${INSPECTOR_URL:https://ingest.inspector.dev}
    version: ${INSPECTOR_VERSION:1.0.1}
    max-entries: ${INSPECTOR_MAX_ENTRIES:500}
